# Generated by Django 5.0.7 on 2024-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=100)),
                ('grade', models.CharField(choices=[('XII', 'XII'), ('XI', 'XI'), ('X', 'X'), ('IX', 'IX'), ('VIII', 'VIII'), ('VII', 'VII'), ('VI', 'VI'), ('V', 'V'), ('IV', 'IV'), ('III', 'III'), ('II', 'II'), ('I', 'I')], default=None, max_length=4)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default=None, max_length=1)),
                ('house', models.CharField(choices=[('RED', 'RED'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default=None, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Student List',
            },
        ),
    ]
