# Generated by Django 5.0.7 on 2024-09-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_student_list_admission_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_list',
            name='division',
        ),
        migrations.RemoveField(
            model_name='student_list',
            name='grade',
        ),
    ]
