# Generated by Django 5.0.7 on 2024-09-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_remove_student_list_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_list',
            name='division',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default=None, max_length=1, null=True),
        ),
    ]
