# Generated by Django 5.0.7 on 2024-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_student_list_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_list',
            name='division',
        ),
        migrations.AlterField(
            model_name='student_list',
            name='admission_number',
            field=models.IntegerField(default=0),
        ),
    ]
