# Generated by Django 5.0.7 on 2024-09-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidates',
            new_name='Candidate',
        ),
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
