# Generated by Django 5.0.7 on 2024-09-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0002_rename_candidates_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='house',
            field=models.CharField(choices=[('RED', 'RED'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default=None, max_length=10),
        ),
    ]
