# Generated by Django 5.0.7 on 2024-09-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0011_alter_candidate_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='division',
        ),
    ]
