# Generated by Django 5.0.7 on 2024-10-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0012_remove_candidate_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
