# Generated by Django 5.0.7 on 2024-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0014_alter_candidate_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status (ON/OFF)'},
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='', max_length=3),
        ),
    ]
