# Generated by Django 5.0.7 on 2024-10-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0015_alter_status_options_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3),
        ),
    ]
