# Generated by Django 5.0.7 on 2024-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0016_alter_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='election_status_name',
            field=models.CharField(default='Election Campaign Status', max_length=100),
        ),
    ]
