# Generated by Django 5.0.7 on 2024-10-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0017_status_election_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='election_status_name',
            field=models.CharField(default='Election Campaign Status', editable=False, max_length=100),
        ),
    ]
